function [Signal,Sample] = Time2Freq(g,H)

% [Signal,Sample] = Time2Freq(g,H)
%
% This routine sets a Fourier transform integration scheme to solve
% the problem based on the input parameters in the time domain. The
% time-dependent forcing will be defined and a sampling procedure will be
% deduced by defining a relevant sampling frequency.

%% Definition of the time-dependent wave forcing generated by a wavemaker 
Signal = InputSignalDef(g,H);

%% Sampling the signal
Sample = SamplingDef(Signal);