%% citeph_SM_EPstruct.m
%% Author: Timothy Williams
%% Date:   20130716, 11:52:02 CEST
function [EP,SM]  = citeph_SM_EPstruct(freqs,nfft,method_num)

nf    = length(freqs);
%nfft  = 2*df;

methods  = {'DFTM',...
            'EMLM',...
            'IMLM',...
            'EMEP',...
            'BDM' };

nd    = 32;
iter  = 1;
EP    = struct('method',methods{method_num},...
               'nfft',nfft,...
               'dres',nd,...
               'iter',iter,...
               'smooth','off');

dres  = 360/nd;
dirs  = (0:nd-1)'*dres;
xdir  = 0;
S     = zeros(nf,nd);
SM    = struct('freqs',freqs,...
               'dirs',dirs,...
               'S',S,...
               'xaxisdir',xdir);
